Preparing training and test sets
Traceback (most recent call last):
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 235, in _has_valid_tuple
    self._validate_key(k, i)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2035, in _validate_key
    "a [{types}]".format(types=self._valid_types)
ValueError: Can only index by location with a [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 95, in <module>
    x_train, y_train = create_dataset(train, look_back=look_back)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 60, in create_dataset
    series_x, series_y = get_series(transactions, look_back)
  File "/Users/michele/Fraud_Detection_LSTM_Thesis/LSTM_classifier.py", line 41, in get_series
    isFraudolent = transactions.iloc[0:look_back, "isFraud"].max()
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2092, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 239, in _has_valid_tuple
    "[{types}] types".format(types=self._valid_types)
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types
PyDev console: starting.

Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
                                      Timestamp   Importo  \
indice                                                      
20141220164514490000328898  2014-12-20 16:04:36  0.030500   
20141231154514807000411159  2014-12-31 15:37:02  0.093078   
20141128154605390000701214  2014-11-28 15:17:46  0.012000   
20141128154605405000605392  2014-11-28 15:18:31  0.015036   
20141128154605499000996878  2014-11-28 15:20:10  0.025100   
20150103214513527000981477  2015-01-03 21:18:19  0.020005   
20150204204223494000156898  2015-02-04 20:21:56  0.002000   
20141212144536756000543697  2014-12-12 14:24:13  0.000396   
20141118074613424000170799  2014-11-18 07:16:28  0.011000   
20150219102741808000455013  2015-02-19 10:16:21  0.003240   
20150219102741824000630514  2015-02-19 10:21:05  0.004335   
20141105134539285000438489  2014-11-05 12:47:37  0.007926   
2014110513453951900038943   2014-11-05 12:49:37  0.010000   
20141114174624418000164266  2014-11-14 17:38:15  0.000800   
20141123084512220000403776  2014-11-23 07:51:40  0.004000   
20141127144630571000434484  2014-11-27 14:34:48  0.040000   
20141127144630649000889485  2014-11-27 14:36:17  0.005273   
20141130204529550000920493  2014-11-30 19:47:35  0.011000   
20141130204529566000659479  2014-11-30 19:51:37  0.000500   
20141130204529582000220038  2014-11-30 19:55:39  0.001100   

                                                      UserID  NumConfermaSMS  \
indice                                                                         
20141220164514490000328898  cd028892a4b9b49f84d787cc587022b4               1   
20141231154514807000411159  6dcbac66f4a535145a12b922341c06df               1   
20141128154605390000701214  01b79c6f4c9119ef0c95ce13b4367ee0               1   
20141128154605405000605392  01b79c6f4c9119ef0c95ce13b4367ee0               1   
20141128154605499000996878  01b79c6f4c9119ef0c95ce13b4367ee0               1   
20150103214513527000981477  0f623dfc2085ea0eed7b1b42ae54425c               1   
20150204204223494000156898  ce6ad499c96de41ae3228fef5d6352dc               1   
20141212144536756000543697  64ed68e466ba66efabc9de30fd6997b6               1   
20141118074613424000170799  fe30e3bf82366aa6bac955fff72a97a2               1   
20150219102741808000455013  26845cc976879853ecfe4100b2d8d5b6               1   
20150219102741824000630514  26845cc976879853ecfe4100b2d8d5b6               1   
20141105134539285000438489  ec9af8a4b333cd2aa2387437177bd588               1   
2014110513453951900038943   ec9af8a4b333cd2aa2387437177bd588               1   
20141114174624418000164266  738371f4976eb93185155634abb36b66               1   
20141123084512220000403776  6cdddf44d1cfad54a412bb009e4de8ac               1   
20141127144630571000434484  c91bc22203e951ee1a1ee43b4ba9a47b               1   
20141127144630649000889485  c91bc22203e951ee1a1ee43b4ba9a47b               1   
20141130204529550000920493  68f33e9248c0082ab2615f54fbba1c5f               1   
20141130204529566000659479  68f33e9248c0082ab2615f54fbba1c5f               1   
20141130204529582000220038  68f33e9248c0082ab2615f54fbba1c5f               1   

                            isFraud  isItalianSender  isItalianReceiver  
indice                                                                   
20141220164514490000328898        0                1                  1  
20141231154514807000411159        0                1                  1  
20141128154605390000701214        0                1                  1  
20141128154605405000605392        0                1                  1  
20141128154605499000996878        0                1                  1  
20150103214513527000981477        0                1                  1  
20150204204223494000156898        0                1                  1  
20141212144536756000543697        0                1                  1  
20141118074613424000170799        0                1                  1  
20150219102741808000455013        0                1                  1  
20150219102741824000630514        0                1                  1  
20141105134539285000438489        0                1                  1  
2014110513453951900038943         0                1                  1  
20141114174624418000164266        0                1                  1  
20141123084512220000403776        0                1                  1  
20141127144630571000434484        0                1                  1  
20141127144630649000889485        0                1                  1  
20141130204529550000920493        0                1                  1  
20141130204529566000659479        0                1                  1  
20141130204529582000220038        0                1                  1  
Traceback (most recent call last):
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 235, in _has_valid_tuple
    self._validate_key(k, i)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2035, in _validate_key
    "a [{types}]".format(types=self._valid_types)
ValueError: Can only index by location with a [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2092, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/michele/PycharmProjects/varie/venv/lib/python3.6/site-packages/pandas/core/indexing.py", line 239, in _has_valid_tuple
    "[{types}] types".format(types=self._valid_types)
ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types
indice
20141220164514490000328898    0
20141231154514807000411159    0
20141128154605390000701214    0
20141128154605405000605392    0
20141128154605499000996878    0
20150103214513527000981477    0
20150204204223494000156898    0
20141212144536756000543697    0
20141118074613424000170799    0
20150219102741808000455013    0
20150219102741824000630514    0
20141105134539285000438489    0
2014110513453951900038943     0
20141114174624418000164266    0
20141123084512220000403776    0
20141127144630571000434484    0
20141127144630649000889485    0
20141130204529550000920493    0
20141130204529566000659479    0
20141130204529582000220038    0
Name: isFraud, dtype: int64
